#  __  __ ___ ____ ____   ___   ____    _    __  __ _____ ____
# |  \/  |_ _/ ___|  _ \ / _ \ / ___|  / \  |  \/  | ____/ ___|
# | |\/| || | |   | |_) | | | | |  _  / _ \ | |\/| |  _| \___ \
# | |  | || | |___|  _ <| |_| | |_| |/ ___ \| |  | | |___ ___) |
# |_|__|_|___\____|_|_\_\\___/_\____/_/   \_\_|  |_|_____|____/
#  / ___/ _ \| \ | |  ___|_ _/ ___|
# | |  | | | |  \| | |_   | | |  _
# | |__| |_| | |\  |  _|  | | |_| |
#  \____\___/|_| \_|_|   |___\____|
# Version: 1.0-SNAPSHOT (Unfinished)
# Author: Interryne/jluvisi2021
# Github: https://github.com/jluvisi2021/MicroGames
# JavaDoc: https://jluvisi2021.github.io/MicroGames/
# If you need to reload your configuration, have lost comments, or have other problems then go to the github "HELP" section in README.md! :D
#
# PLACEHOLDERS (for Messages):
# NOTE: Not all placeholders may work for all messages. Use common sense when figuring out which placeholders work.
# (Ex. Don't try and call %time_left% on a message like "We could not find this game".)
#
# %player% -> Name of player.
# %world% -> Get the name of the world the player is in.
# %hunger% -> Get the current hunger level of the player.
# %health% -> Get the current health of the player.
# %time_left% -> Time left until lobby starts.
# %players_needed% -> Players needed to start the game.
# %players_in_lobby% -> The current amount of players in the lobby.
# %max_players_allowed% -> The maximum allowed number of players in a lobby.
# %game_name% -> Name of the current game.
# %argument_error% -> The argument a player types in a command where the argument is invalid. (Ex. /microgames join test -> "The game %argument_error% does not exist.")
#
####### DO NOT EDIT #######
major-config-version: "1.0"
###########################

# Messages in the plugin.
messages:
  general:
    must-be-player: "&cYou must be a player to execute this command!"
    no-permission: "&cYou do not have permission to execute this command!"
    game-signs-disabled: "&cGame signs are currently disabled!"
  lobby:
    game-full: "&cThe game is currently full!"
    game-in-progress-or-disabled: "&cYou cannot join this game right now."
    already-in-game: "&cYou are already in this game."
    must-leave-game: "&cYou must leave your current game to join that game."
    player-lobby-join: "&7Joined Lobby: &6%game_name%"
    global-player-lobby-join: "&a%player% &7has joined the lobby! &8(&e%players_in_lobby%&7/&6%max_players_allowed%&8)&7."
    game-starting: "&7Game Starting in: &a%time_left% seconds!"
    players-needed: "&6%players_needed% players &7needed to start the game!"
    player-cant-leave: "&cYou cannot leave a game because you are not in one."
    global-player-leave: "&a%player% &7has left the lobby! &8(&e%players_in_lobby%&7/&6%max_players_allowed%&8)&7."
    leave-game: "&cYou left the game!"
  game:
    could-not-find-game: "&cThe game '%argument_error%' could not be found."
    game-created-notify: "&7[&c&l!&7] &aA new MicroGame's lobby has been created! &6/microgames join %game_name% to join!"
    game-created-1: "&aSuccessfully created game: &6%game_name%"
    game-created-2: "&7Players can join this game through the command: &6/microgames join %game_name%"

# Permissions
permissions:
  reload-config: "microgames.reload"
  setup-game-sign: "microgames.setupsign"
  destroy-game-sign: "microgames.destroysign"
  use-join-sign: "microgames.join.sign"
  join-game: "microgames.join"
  leave-game: "microgames.leave"
  start-game: "microgames.start"
  notify-announce-game-start: "microgames.notify"

# Enable game signs. (Games can still be run with "/microgames start <param>")
# You can edit the individual lines and colors of a sign when it is placed except for the first line (color can be adjusted).
# Placeholders. %game_name%, %curr_players%, %max_players%, %winning_score%, %min_players%, %game_state%
game-signs:
  enabled: true
  sign-material: "OAK" # DARK_OAK, ACACIA, SPRUCE, etc
  line1-color: "&0&l"
  line2: "%curr_players%/%max_players%"
  line3: "Winning Score: &9&l%winning_score%"
  line4: "&lCLICK TO JOIN"
  game-full-color-line: 2 # The line to change on the sign when the game is full.
  game-full-color: "&4" # The color to change that line.

  # If clicking the sign should execute extra commands. You do not need a slash.
  # The command is only executed if the sign is successfully joined.
  # The top will execute commands like the player is doing them while the bottom will execute from the console.
  # use %player% for player name
  execute-player-commands:
#  - "me Testing 123...%player%"
  execute-console-commands:
#  - "give %player% minecraft:cooked_beef 1"

